---
title: "Analisis para presentación de avance"
author: "Martín Venegas"
date: "4/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!require("pacman")) install.packages("pacman")  #si falta pacman, instalar
if (!require("tinytex")) install.packages("tinytex")#si falta tinytex, instalar
pacman::p_load(knitr, summarytools, kableExtra, dplyr, lavaan, haven, htmlwidgets, webshot, sjPlot, VIM, GGally, finalfit, table1, ordinal,gtsummary, sjmisc, sjlabelled) # librerias
```


```{r}
load("input/data/procjv_conf_nona.RData")
```


```{r}
#modelo
procjv_conf_nona$jv_carab1_2019_factor <- sjlabelled::set_label(procjv_conf_nona$jv_carab1_2019_factor, label = "Justificacion violencia:Carabineros reprime marchas") 

jv_carab1 <- clm(jv_carab1_2019_factor ~ trato_salud_factor + trato_carab_factor + sj_ceo_cat_factor + sj_obrero_cat_factor + sj_entrevistado_cat_factor + sexo_factor + educ_rec_factor + ingreso, data = procjv_conf_nona)

jvjv <- tab_model(jv_carab1, transform = NULL, drop = c("Nunca se justifica|Pocas veces se justifica",
                                                "Pocas veces se justifica|Algunas veces se justifica",
                                                "Algunas veces se justifica|Muchas veces se justifica",
                                                "Muchas veces se justifica|Siempre se justifica",
                                                "trato_salud_factorA veces",
                                                "trato_salud_factorCasi siempre",
                                                "trato_salud_factorSiempre",
                                                "trato_carab_factorCasi nunca",
                                                "trato_carab_factorA veces",
                                                "sj_ceo_cat_factorSubrecompensado",
                                                "sj_ceo_cat_factorSobrerecompensado",
                                                "sj_obrero_cat_factorSobrerecompensado",
                                                "sj_entrevistado_cat_factorSubrecompensado",
                                                "sj_entrevistado_cat_factorSobrerecompensado",
                                                "ingreso"
                                                ),encoding = "Windows-1252")


jv_est1 <- clm(jv_est_2019_factor ~ trato_salud_factor + trato_carab_factor + sj_ceo_cat_factor + sj_obrero_cat_factor + sj_entrevistado_cat_factor + sexo_factor + educ_rec_factor + ingreso, data = procjv_conf_nona)

tab_model(jv_est1)
```

```{r out.height= 10, out.width= 7}
jvjv
```


```{r fig.height= 15, fig.width= 15}
plot_model(jv_carab1,transform = NULL, axis.labels = c("Ingresos",
                                                       "Educacion|Terciaria y Postgrado",
                                                       "Educacion|Terciaria Ciclo Corto",
                                                       "Educacion|Secundaria Alta",
                                                       "Educacion|Primaria y Secundaria Baja (ref: Primaria Incompleta y Menos)",
                                                       "Sexo|Mujer (ref: Hombre)",
                                                       "Sentido Justicia Entrevistado|Sobrerecompensado",
                                                       "Sentido Justicia Entrevistado|Subrecompensado (ref: Justo)",
                                                       "Sentido Justicia Obrero|Sobrerecompensado",
                                                       "Sentido Justicia Obrero|Subrecompensado (ref: Justo)",
                                                       "Sentido Justicia Gerente|Sobrerecompensado",
                                                       "Sentido Justicia Gerente|Subrecompensado (ref: Justo)",
                                                       "Trato Respetuoso Carabineros|Siempre", 
                                                       "Trato Respetuoso Carabineros|Casi siempre", 
                                                       "Trato Respetuoso Carabineros|A veces", 
                                                       "Trato Respetuoso Carabineros|Casi nunca (ref: Nunca)"),
                                                       # "Trato Respetuoso Servicios Salud|Siempre", 
                                                       # "Trato Respetuoso Servicios Salud|Casi siempre", 
                                                       # "Trato Respetuoso Servicios Salud|A veces", 
                                                       # "Trato Respetuoso Servicios Salud|Casi nunca (ref: Nunca)"),
           rm.terms = c("trato_salud_factor"))
```

